### ISSUE TITLE
The provided configuration cannot be parsed. No parser exists for kind: [null]

### ISSUE THREAD

**Issue by tatarco** [egoshard/intellij-k8s-runtime-config#1]
Hello,
my team was really excited about this plugin but we are having hard time getting it to work
while trying to load a yaml file in the written in the following format
`replicaCount: 1

image:
  repository_tag: someValue
  pullPolicy: someValue
  containerPort: someValue
  healthcheck: someValue
  initialDelaySeconds: someValue
  timeoutSeconds: someValue

service:
  port: someValue

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: someValue
  path: ""
  host: someValue

resources:
  limits:
    cpu: 1000m
    memory: 1200Mi
  requests:
    cpu: 500m
    memory: 1200Mi

hpa:
  enabled: false

secret:
  enabled: true
  stringData:
    PRODUCTION_DEPLOYMENT_TYPE: someValue
    ENV: someValue
    ASSET_SERVER_URL: someValue
    MONGO_HOST: someValue
    MONGO_PORT: someValue
    MONGO_SLAVE_1_HOST: someValue
    MONGO_SLAVE_1_PORT: someValue
    MONGO_SLAVE_2_HOST: someValue
    MONGO_SLAVE_2_PORT: someValue
    MONGO_USER: someValue
    MONGO_PASSWORD: someValue
    MONGO_DB: someValue
    MONGO_ENABLE_SSL: someValue
    ES_CLUSTER_NAME: someValue
    ES_SERVER1: someValue
    ES_SERVER2: someValue
    ES_SERVER3: someValue
    ES_MAX_TOTAL_CONNECTION: someValue
    ES_DEFAULT_MAX_TOTAL_CONNECTION_PER_ROUTE: someValue
    ES_CONN_TIMEOUT: someValue
    ES_READ_TIMEOUT: someValue
    RABBIT_HOST: someValue
    NOTIFICATION_SERVICE_URL: someValue
    S3_BUCKET: someValue
    CDN_ASSETS_GENERAL_DOMAIN: someValue
    CDN_VIDEOS_DOMAIN: someValue
    CDN_ASSETS_DOMAIN: someValue
    CDN_ASSETS_DOMAIN_PROD: someValue
    CDN_NUM_OF_ALIASES: someValue

nodeSelector: {}

tolerations: []

affinity: {}
`
the file is added to the run configurations, the plugin is enabled but at runtime it fails
checking in the idea.log i see the following exception:

Caused by: com.egoshard.intellij.k8s.ConfigFileException: The provided configuration cannot be parsed. No parser exists for kind: [null].
	at com.egoshard.intellij.k8s.ConfigEntry.parse(ConfigEntry.java:58)
	at com.egoshard.intellij.k8s.ui.ConfigEditor.parse(ConfigEditor.java:161)

**Comment by egoshard** [comment]
Sorry for the extreme delay but the file you have doesn't appear to have the correct structure for a configmap or secret. The error you are receiving is due to there being no `kind` definition in your file.
Kubernetes configuration files have a structure that defines the kind of object that it describes, for example a ConfigMap generally looks like this:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-service-configmap
  namespace: development
```
Entries can be strung together in a single file by separating then with dashes, like this:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-service
  namespace: development
spec:
  selector:
    matchLabels:
  replicas: 1
  template:
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: development
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-service-configmap
  namespace: development
```
If you are still having this issue, can you please attach a file and I will investigate if there is a defect in the plugin.
